# Use the official Python image as the base image
FROM python:3.12

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Python source code files into the container
COPY . .

# Expose the port the API will run on
EXPOSE 8000

# Command to run the API when the container starts
CMD ["python", "app.py"]
